#Customization of the plugin, you mustn't touch this lines, only the ones without #

#Basics--------------------------------
Prefix: '&8[&bFly&8]&r '
NoPerms: '&cNo tienes permisos!'
NotFound: '&cComando no encontrado!'
#--------------------------------------

#FlyCommands-------------------------------------------
PlayerOffline: '&cEl jugador &b%player_name% &cestar conectado!'
FlyEnabled: '&eModo de vuelo activado!'
FlyDisabled: '&eModo de vuelo desactivado!'
FlyEnabledOther: '&eModo de vuelo activado por&b %player_name%&e!'
FlyDisabledOther: '&eModo de vuelo desactivado por&b %player_name%&e!'
SpecifyAPlayer: '&cDebes especificar a un jugador!'
FlyEnabledBy: '&eModo de vuelo activado para&b %player_name%&e!'
FlyDisabledBy: '&eModo de vuelo desactivado para&b %player_name%&e!'
FlyEnabledEveryone: '&eTodos a volar!'
FlyDisabledEveryone: '&eSe ha terminado la diversion! :('
#-------------------------------------------------------

#Help---------------------------------------------------
HelpSpacers: '&7&m---------------------------------------------------'
HelpTitle: '                        &bSimpleFly &eHelp'
FlyCommand: '&8路 &b/fly &7&m--&r&7> &eEnable or Disable flight mode!'
FlyOtherCommand: '&8路 &b/flyto &7&m--&r&7> &eEnable or Disable flight mode to another player!'
FlyAllCommand: '&8路 &b/flyall &7&m--&r&7> &eEnable or Disable flight mode for everyone!'
ReloadCommand: '&8路 &b/flyreload &7&m--&r&7> &eReload the Config files!'
#-------------------------------------------------------

#Gui Configuration--------------------------------------
GuiTitle: '&bFly'
Feather: '&bFly'
FeatherLore: '&eActiva tu fly!'
FlyOther: '&bActiva fly a otra persona'
FlyOtherLore: '&eClick para ver los jugadores'
FlyAll: '&bActiva el fly para todos'
FlyAllLore: '&eClick para activar el fly'
Exit: '&cSalir'
ExitLore: '&7Click para cerrar el menu'
#-------------------------------------------------------

#ReloadMessages-----------------------------------------
Reload: '&ePlugin recargandose.'
ReloadDone: '&aEl plugin ha sido recargado con exitosamente.'
ReloadFailed: '&cEl plugin no ha sido recargado, revisa la consola.'
#--------------------------------------------------------

#--------------------------------------------------------------------
Player join, fly is enabled/disabled/none: enabled
#--------------------------------------------------------------------



